FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY src/backend/package*.json ./
COPY src/backend/prisma ./prisma/

RUN npm install --ignore-scripts
RUN npx prisma generate

COPY src/backend/ .

EXPOSE 3000

CMD ["node", "server.js"]
