FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY src/bot/package*.json ./
COPY src/bot/prisma ./prisma/

RUN npm install --ignore-scripts
RUN npx prisma generate

COPY src/bot/ .

CMD ["node", "bot.js"]
